services:
  database:
    image: mongo
    container_name: iot-database
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=iotdb
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password      
    volumes:
      - ./config-database/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - iot_data:/data/db   
    networks:
      - network-name

  broker:
    image: eclipse-mosquitto
    container_name: iot-broker
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./config-broker:/mosquitto/config
      - broker_data:/mosquitto/data
      - broker_log:/mosquitto/log
    networks:
      - network-name

  gateway:
    image: nodered/node-red  
    container_name: ito-gateway
    ports:
      - 1880:1880
      - 1885:1885
    environment:
      - TZ=Europe/Madrid
    networks:
      - network-name

volumes:
  iot_data:
  broker_data:
  broker_log:

networks:
    network-name:
      name: uniovi
